apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: app
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [us-east-1a, us-east-1b, us-east-1c]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
        - t3a.medium
  limits:
    resources:
      cpu: 30
  providerRef:
    name: default
  labels:
    type: karpenter
    provisioner: app
  taints:
    - key: provisioner/app
      effect: NoSchedule
  consolidation:
    enabled: true
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads (excluding daemons)
  ttlSecondsUntilExpired: 604800 # expire nodes after 7 days (in seconds) = 7 * 60 * 60 * 24
