---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: quickbooks2018/green:latest
        name: app1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: app1
spec:
  ports:
  - port: 80
    protocol: TCP
  type: ClusterIP
  selector:
    app: app1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  namespace: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: cloudgeeksca
spec:
  ingressClassName: alb
  rules:
    - host: app1.saqlainmushtaq.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: app1
                port:
                  number: 80